# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_backend_option_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.option:indexAction
        _template: SyliusWebBundle:Backend/Option:index.html.twig
        _sortable: true
        _sorting:
            name: desc

sylius_backend_option_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.option:createAction
        _template: SyliusWebBundle:Backend/Option:create.html.twig
        _redirect: sylius_backend_option_index

sylius_backend_option_update:
    pattern: /{id}/edit
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.option:updateAction
        _template: SyliusWebBundle:Backend/Option:update.html.twig
        _redirect: sylius_backend_option_index

sylius_backend_option_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.option:deleteAction
        _redirect: sylius_backend_option_index
