# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_backend_product_index:
    pattern: /index
    defaults:
        _controller: sylius.controller.product:indexAction
        _template: SyliusWebBundle:Backend/Product:index.html.twig
        _sortable: true
        _sorting:
            name: desc
    requirements:
        _method: GET

sylius_backend_product_create:
    pattern: /new
    defaults:
        _controller: sylius.controller.product:createAction
        _template: SyliusWebBundle:Backend/Product:create.html.twig
        _redirect: sylius_backend_product_show
    requirements:
        _method: GET|POST

sylius_backend_product_update:
    pattern: /{id}/edit
    defaults:
        _controller: sylius.controller.product:updateAction
        _template: SyliusWebBundle:Backend/Product:update.html.twig
        _redirect: sylius_backend_product_show
    requirements:
        _method: GET|PUT

sylius_backend_product_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius.controller.product:deleteAction
        _redirect: sylius_backend_product_index

sylius_backend_product_show:
    pattern: /{id}
    defaults:
        _controller: sylius.controller.product:showAction
        _template: SyliusWebBundle:Backend/Product:show.html.twig
    requirements:
        _method: GET
