# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_backend_general_settings:
    pattern: /general
    defaults:
        _controller: sylius.controller.settings:updateAction
        namespace: general
        template: SyliusWebBundle:Backend/Settings:general.html.twig

