# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_backend_tax_rate_index:
    pattern: /index
    defaults:
        _controller: sylius_taxation.controller.rate:indexAction
        _template: SyliusWebBundle:Backend/TaxRate:index.html.twig
        _sortable: true
        _sorting:
            name: desc
    requirements:
        _method: GET

sylius_backend_tax_rate_create:
    pattern: /new
    defaults:
        _controller: sylius_taxation.controller.rate:createAction
        _template: SyliusWebBundle:Backend/TaxRate:create.html.twig
        _redirect: sylius_backend_tax_rate_show
    requirements:
        _method: GET|POST

sylius_backend_tax_rate_update:
    pattern: /{id}/edit
    defaults:
        _controller: sylius_taxation.controller.rate:updateAction
        _template: SyliusWebBundle:Backend/TaxRate:update.html.twig
        _redirect: sylius_backend_tax_rate_show
    requirements:
        _method: GET|PUT

sylius_backend_tax_rate_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius_taxation.controller.rate:deleteAction
        _redirect: sylius_backend_tax_rate_index

sylius_backend_tax_rate_show:
    pattern: /{id}
    defaults:
        _controller: sylius_taxation.controller.rate:showAction
        _template: SyliusWebBundle:Backend/TaxRate:show.html.twig
    requirements:
        _method: GET
