# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_backend_taxon_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.taxon:deleteAction
        _redirect: referer
