# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_backend_taxonomy_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.taxonomy:indexAction
        _template: SyliusWebBundle:Backend/Taxonomy:index.html.twig
        _sortable: true
        _paginate: 50

sylius_backend_taxonomy_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.taxonomy:createAction
        _template: SyliusWebBundle:Backend/Taxonomy:create.html.twig
        _redirect: sylius_backend_taxonomy_show

sylius_backend_taxonomy_update:
    pattern: /{id}/edit
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.taxonomy:updateAction
        _template: SyliusWebBundle:Backend/Taxonomy:update.html.twig
        _redirect: sylius_backend_taxonomy_show

sylius_backend_taxonomy_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.taxonomy:deleteAction
        _redirect: sylius_backend_taxonomy_index

sylius_backend_taxonomy_show:
    pattern: /{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.taxonomy:showAction
        _template: SyliusWebBundle:Backend/Taxonomy:show.html.twig
