# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_backend_user_index:
    pattern: /index
    defaults:
        _controller: sylius.controller.user:indexAction
        _template: SyliusWebBundle:Backend/User:index.html.twig
        _filterable: true
        _sortable: true
        _sorting:
            id: desc
    requirements:
        _method: GET

sylius_backend_user_delete:
    pattern: /{id}
    defaults:
        _controller: sylius.controller.user:deleteAction
    requirements:
        _method: DELETE

sylius_backend_user_show:
    pattern: /{id}
    defaults:
        _controller: sylius.controller.user:showAction
        _template: SyliusWebBundle:Backend/User:show.html.twig
    requirements:
        _method: GET
