# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_backend_zone_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.zone:indexAction
        _template: SyliusWebBundle:Backend/Zone:index.html.twig
        _sortable: true

sylius_backend_zone_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.zone:createAction
        _template: SyliusWebBundle:Backend/Zone:create.html.twig
        _redirect: sylius_backend_zone_show

sylius_backend_zone_update:
    pattern: /{id}/edit
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.zone:updateAction
        _template: SyliusWebBundle:Backend/Zone:update.html.twig
        _redirect: sylius_backend_zone_show

sylius_backend_zone_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.zone:deleteAction
        _redirect: sylius_backend_zone_index

sylius_backend_zone_show:
    pattern: /{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.zone:showAction
        _template: SyliusWebBundle:Backend/Zone:show.html.twig
